# dependabot config for npm

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    open-pull-requests-limit: 10
    schedule:
      interval: "weekly"
      day: "thursday"
    groups:
      storybook:
        patterns:
          - "@storybook*"
          - "storybook*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      
