# dependabot config for npm

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    open-pull-requests-limit: 10
    schedule:
      interval: "weekly"
      day: "thursday"
    cooldown:
      default-days: 1
    groups:
      react-deps:
        patterns:
          - "react"
          - "react-dom"
          - "@types/react"
          - "@types/react-dom"
      storybook:
        patterns:
          - "@storybook*"
          - "storybook*"
      lint:
        patterns:
          - "eslint*"
          - "@eslint*"
          - "globals"
          - "typescript-eslint"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      
